# $lic$
# Copyright (C) 2015 by Massachusetts Institute of Technology
#
# This file is part of libspin.
#
# libspin is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, version 2.
#
# libspin is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.

Import('env')
progEnv = env.Clone()
progEnv.Append(LINKFLAGS = ['-static']) # better PC-based debugging
srcs = Glob('*.cpp') + Glob('*.s')
progs = map(lambda f: str(f).split("/")[-1].split(".")[0], srcs)

for (prog, src) in zip(progs, srcs):
    if src.path.endswith(".s"):
        progEnv.Program(target = prog, source=src, LINKFLAGS=['-nostdlib'])
    else:
        progEnv.Program(target = prog, source=src)
