# $lic$
# Copyright (C) 2015 by Massachusetts Institute of Technology
#
# This file is part of libspin.
#
# libspin is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, version 2.
#
# libspin is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.

Import('env')
slowEnv = env.Clone()
slowEnv['CPPFLAGS'] += ['-DSPIN_SLOW']
slowEnv['OBJSUFFIX'] = '.oslow'

spinFast = env.StaticLibrary(target = 'libspin_fast.a', source='spin_fast.cpp')
spinSlow = slowEnv.StaticLibrary(target = 'libspin_slow.a', source='spin_slow.cpp')
libs = (spinFast, spinSlow)
Return('libs')
