# $lic$
# Copyright (C) 2015 by Massachusetts Institute of Technology
#
# This file is part of libspin.
#
# libspin is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, version 2.
#
# libspin is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.

from __future__ import (absolute_import, division, print_function)

Import('env', 'speed')

assert speed in ['fast', 'slow']

libEnv = None
if speed == 'slow':
    libEnv = env.Clone()
    libEnv.Append(CPPDEFINES = 'SPIN_SLOW')
    libEnv['OBJSUFFIX'] = '.oslow'
else:
    libEnv = env

lib = libEnv.StaticLibrary(target='libspin_{}.a'.format(speed),
                           source='spin.cpp')
Return('lib')
