# $lic$
# Copyright (C) 2015-2020 by Massachusetts Institute of Technology
#
# This file is part of libspin.
#
# libspin is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, version 2.
#
# libspin was developed as part of the Swarm architecture simulator. If you
# use this software in your research, we request that you reference the Swarm
# paper ("A Scalable Architecture for Ordered Parallelism", Jeffrey et al.,
# MICRO-48, 2015) as the source of libspin in any publications that use this
# software, and that you send us a citation of your work.
#
# libspin is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.

from __future__ import (absolute_import, division, print_function)

Import('env', 'speed')

assert speed in ['fast', 'slow']

libEnv = env.Clone()
if speed == 'slow':
    libEnv.Append(CPPDEFINES = 'SPIN_SLOW')
    libEnv['OBJSUFFIX'] = '.oslow'
else:
    assert speed == 'fast'
    # AVX is required by spin-fast; this compiles SNB-compatible code.
    # To build for an architecture without AVX, use the speed=slow scons option.
    archFlags = ['-march=corei7-avx', '-mavx', '-msse4.1', '-msse4.2']
    libEnv.Append(CPPFLAGS = archFlags)

lib = libEnv.StaticLibrary(target='libspin_{}.a'.format(speed),
                           source='spin.cpp')
Return('lib')
